[[entries]]
id = "bb67aeb5-2ff3-4ef3-812b-2dfae5508742"
type = "feature"
description = "Add `CargoManifest` class"
author = "@NiklasRosenstein"

[[entries]]
id = "cd4c023d-c08e-4dd9-bb24-181b3fc148d8"
type = "improvement"
description = "no longer depend on `proxy.py` as a dependency, instead we expect users to install it separately"
author = "@NiklasRosenstein"
