[[entries]]
id = "d63edec0-7c4a-4516-9d57-a1f260564fda"
type = "improvement"
description = "RenderFileTask no longer tries to call the content supplier in `finalize()`, fix info line on the file being written"
author = "@NiklasRosenstein"
