[[entries]]
id = "a0314a37-7a7a-44dc-8cbe-799f9cbb74b4"
type = "improvement"
description = "remove `RenderFileTask.create_check_task` property in favor of a `.make_check_task()` method, colorize output of `CheckFileContentsTask`"
author = "@NiklasRosenstein"

[[entries]]
id = "c12eca50-f5ae-4c23-8baa-9f11171985fb"
type = "improvement"
description = "add `cargo_sync_config(check)` parameter, enabled by default, to create a check task"
author = "@NiklasRosenstein"

[[entries]]
id = "16a6b247-dc96-4007-b189-b7830875e8cc"
type = "improvement"
description = "`gitignore()` now also generates a check task"
author = "@NiklasRosenstein"

[[entries]]
id = "e6f93e0a-e6c0-4704-ad57-f0eea64016d7"
type = "improvement"
description = "`PythonBuildSystem` now has a class-level `name` attribute"
author = "@NiklasRosenstein"

[[entries]]
id = "384bcb08-f051-4442-bac6-b2490467307d"
type = "improvement"
description = "add task descriptions for Python tasks"
author = "@NiklasRosenstein"

[[entries]]
id = "5f868c43-c4c1-4a2e-bece-83508221fe28"
type = "improvement"
description = "Add descriptions to Cargo tasks and Python build/install tasks"
author = "@NiklasRosenstein"
