[[entries]]
id = "a0314a37-7a7a-44dc-8cbe-799f9cbb74b4"
type = "improvement"
description = "remove `RenderFileTask.create_check_task` property in favor of a `.make_check_task()` method, colorize output of `CheckFileContentsTask`"
author = "@NiklasRosenstein"

[[entries]]
id = "c12eca50-f5ae-4c23-8baa-9f11171985fb"
type = "improvement"
description = "add `cargo_sync_config(check)` parameter, enabled by default, to create a check task"
author = "@NiklasRosenstein"
