[[entries]]
id = "fedc7a5c-60e6-4bcd-ad2f-56b865217c54"
type = "feature"
description = "add `DockerFileTask.create_preprocessor_task(group)` parameter, and set it to `None` by default"
author = "@NiklasRosenstein"
