[[entries]]
id = "d5ca660f-9cd8-47d2-84e7-daf4fd38c9c3"
type = "feature"
description = "Add `DockerBuildTask.platform` property"
author = "@NiklasRosenstein"

[[entries]]
id = "979afe3a-8f89-4e87-859a-b1555543265b"
type = "improvement"
description = "use new `Task.logger` in kraken-core 0.2.4 in `KanikoBuildTask`"
author = "@NiklasRosenstein"
