name: Python application

on:
  push: { branches: [ develop ], tags: [ "*" ] }
  pull_request: { branches: [ develop ] }

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.7", "3.8", "3.9", "3.10", "3.x" ]
    steps:
    - uses: actions/checkout@v2
    - uses: python-slap/slap-cli@gha/install/v1
    - uses: actions/setup-python@v2
      with: { python-version: "${{ matrix.python-version }}" }
    - run: slap install -vv --no-venv-check
    - run: slap test -x pytest-ete

    # Make sure we have Docker available for the ete-tests.
    - uses: docker/setup-buildx-action@v2

    # Import credentials for integration tests.
    - name: Import Secrets
      uses: hashicorp/vault-action@v2.4.0
      with:
        url: ${{ secrets.VAULT_ADDR }}
        token: ${{ secrets.VAULT_TOKEN }}
        secrets: |
          kv/data/projects/github.com/kraken-build/kraken-std cloudsmith.io | CLOUDSMITH_INTEGRATION_TEST_CREDENTIALS ;
          kv/data/projects/github.com/kraken-build/kraken-std niklasrosenstein.jfrog.io | ARTIFACTORY_INTEGRATION_TEST_CREDENTIALS

    - run: slap test pytest-ete


  update-changelog:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v2
      - uses: python-slap/slap-cli@gha/changelog/update/v1
